version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: instant_mechanic_db
    restart: always
    environment:
      POSTGRES_USER: mechanic_admin
      POSTGRES_PASSWORD: instant@123
      POSTGRES_DB: instant_mechanic
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: